### PR TITLE
Add fill property to dict

### PR DESCRIPTION
**Pull request by Maks1mS**
#12

### CODE REVIEW

**Comment by Maks1mS** [comment]
Also, alias of "display" ("d") conflicts with property "d" of SVG. Maybe change "d" to "dp"? 
изображение

**Comment by Eddort** [comment]
Thank you for your PR!
We are researching the possibility of replacing the alias and will let you know the result later.
Thank you for your participation!

**Comment by Maks1mS** [comment]
List of possible conflicts:
| SVG Attributes|description|Conflict|
|-|-|-|
|d|[define a path](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d)|[display](https://github.com/quarkly/atomize/blob/501b7ea69c122bb1dc4072bb280da605b34a402d/src/constants/dict.js#L64)|
|z|[location along the z-axis for a light source](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/z)|[z-index](https://github.com/quarkly/atomize/blob/501b7ea69c122bb1dc4072bb280da605b34a402d/src/constants/dict.js#L127)|
|r|[circle radius](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r)|[right](https://github.com/quarkly/atomize/blob/501b7ea69c122bb1dc4072bb280da605b34a402d/src/constants/dict.js#L129)|

If I find more conflicts I will update the table

**Comment by Eddort** [comment]
Hey, we looked into the problem and found the following solution.
Add the feature to disable the alias system when creating a component using atomize - useAliaes: boolean (default true)
```const MyComp = atomize.svg({effects: {hover: '.hover'}, useAliaes: false})```
https://github.com/quarkly/atomize/pull/14

**Comment by Eddort** [comment]
@Mobydack

**Pull request merged**
